### ISSUE TITLE
On IOS Buy doesnt do anything when called

### ISSUE THREAD

**Issue by westonganger** [AlexDisler/cordova-plugin-inapppurchase#1]
Tested on my IOS 9.2 device but nothings is happening. Is there full support for IOS?

**Comment by AlexDisler** [comment]
Did you get a successful result from ```getProducts()```? The products have to be loaded before making purchases.

Please post the code you used.

**Comment by westonganger** [comment]
Sorry I had a late night when I posted. My function name was missing a capital. Worked like a dream after I fixed this. 

By the way you should really promote this plugin more. This plugin blows the water out out of the other purchase plugin. I might write a blog post about it.

**Comment by AlexDisler** [comment]
Thanks! Let me know if you blog about it.

**Comment by westonganger** [comment]
I just posted the article here: http://solidfoundationwebdev.com/blog/posts/how-to-add-in-app-purchases-to-your-cordova-or-ionic-app

I also posted a link to the article on JSLive.com which should dramatically increase the amount of views. https://jslive.com/p/75pces-how-to-add-in-app-purchases-to-your-cordova-or-ionic-app

**Comment by AlexDisler** [comment]
Awesome! Thank you
