### ISSUE TITLE
Array.find is not available in some environments

### ISSUE THREAD

**Issue by dougflip** [AlexDisler/cordova-plugin-inapppurchase#10]
`Array.find` does not seem to be implemented on Android - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) indicates it is unsupported

### Your code / steps to reproduce
```js
p = inAppPurchase.getProducts(['android.test.purchased'])
```
### Console output
```
Uncaught (in promise) TypeError: val.find is not a function
    at Object.utils.validArrayOfStrings (file:///android_asset/www/plugins/cordova-plugin-inapppurchase/www/index-android.js:23:62)
    at file:///android_asset/www/plugins/cordova-plugin-inapppurchase/www/index-android.js:58:30
    at Object.inAppPurchase.getProducts (file:///android_asset/www/plugins/cordova-plugin-inapppurchase/www/index-android.js:57:10)
    at <anonymous>:2:19
    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

### Type of product you are working with consumable/non-consumable/subscription

Calling `inAppPurchase.getProducts` for a consumable product on Android.

### Version of cordova

6.0.0

### Version of iOS/Android

6.0.1 (running in Crosswalk 17 via cordova-plugin-crosswalk-webview 1.6.0)

### Notes

For now I am just using the polyfill provided by MDN and that works fine. I was just unsure if that was something I should be doing or if you intended to bundle that within the plugin. Thanks!

**Comment by AlexDisler** [comment]
polyfill added https://github.com/AlexDisler/cordova-plugin-inapppurchase/commit/1968e41d173481eb2e6a536fdc55cc9e9253e6d5

**Comment by objectiveP** [comment]
It is also not available on the iOS7 Webview.
