### ISSUE TITLE
getReceipt() unpredictable behaviour on production environment 

### ISSUE THREAD

**Issue by bigunaleksej** [AlexDisler/cordova-plugin-inapppurchase#101]
When I test functionality with Sandbox and production users I have different behavior of getReceipt method.

Development (Sandbox users):
1. Go to iTunes settings and log out.
2. Go to application, invoke method "getReceipt()" and as result iOS show me pop up with options use existing AppleID or create new one.
3. I pick use existing, enter login and password for Sandbox user and iTunes send me valid Receipt

Production (Real users)
1. I'm logged in iTunes ("user_1") go to AppStrore and download app
2. Go to iTunes settings and log out "user_1" (as option we can log in "user_2". It doesn't affect next steps).
3. Go to application, invoke method "getReceipt()" and as result iOS show me pop up where system ask me enter password for ("user_1").

As for me is unpredictable. And what I can do with it if I need to get flow like with Sandbox users.

### Your code / steps to reproduce
```js
  inAppPurchase.getReceipt()
     .then((receipt) -> {
        ...some logic (including case when I wish restore subsciption)
     })
     .catch((err) -> {
       ...error handling
     })
```
### Type of product you are working with consumable/non-consumable/subscription
auto-renewing subscriptions
### Version of cordova
6.3.1
### Version of iOS/Android
iOS 9 and 10

Thanks

**Comment by Seoptics** [comment]
As 'user_1' downloaded the iOS will asked password for that user, not 'user_2'. The app is bound to user_1.

**Comment by bigunaleksej** [comment]
Yes thanks. I asked iTunes support they already answer me.
“StoreKit is designed so that there is just one current iTunes user associated with an app at any one time. What you are asking foe would be an enhancement request for multi StoreKit user support”.
So I close this issue.
