### ISSUE TITLE
Issue with installation?

### ISSUE THREAD

**Issue by moontz** [AlexDisler/cordova-plugin-inapppurchase#102]
Hi - I am being told that I am unable to install because I do not have cordova version >= 5.  But if I run cordova -v, it says I am running 5.3.3.  Is this a known issue or am I not understanding the install process?

_Installing "cordova-plugin-inapppurchase" for ios
Plugin doesn't support this project's cordova version. cordova: 3.7.0, failed version requirement: >=5.0.0
Skipping 'cordova-plugin-inapppurchase' for ios_

**Comment by skotturi** [comment]
@moontz my guess is that your ios/android project's were configured with a previous version of cordova. 

try running:
```
cordova platform remove ios
cordova platform add ios
```

that will rebuild the ios platform with the latest version of cordova you have installed. 
repeat for android if youre using android as well.
