### ISSUE TITLE
How to test iOS, iTunesConnect reports different from instructions here

### ISSUE THREAD

**Issue by skotturi** [AlexDisler/cordova-plugin-inapppurchase#107]
According to: 
https://alexdisler.com/2016/04/04/testing-cordova-in-app-purchases-on-ios-android/

it says:

> Testing on iOS
> On iOS you can start testing your app right away and there is no setup required for the app. However, you will need to create a sandbox tester account and use it for all test purchases.

However, when I create a new IAP in iTunesConnect it get:

> Your first In-App Purchase must be submitted with a new app version. Select it from the app’s In-App Purchases section and click Submit.
> Once your binary has been uploaded and your first In-App Purchase has been submitted for review, additional In-App Purchases can be submitted using the table below.

If you recently built an iOS implementation using this plugin, how did you test your IAPs? 

Some relevant details: 
1. my IAP is an auto-renewing subscription

TIA, Sante

**Comment by mlegenhausen** [comment]
Just create the IAP it does not need to be reviewed. The iTunesConnect documentation is for production usage only. After creation you should be able to fetch the product via the plugins API. For testing the purchase you need the described test user.

**Comment by skotturi** [comment]
Great, thanks for the clarification!
