### ISSUE TITLE
Update README - Subscriptions

### ISSUE THREAD

**Issue by guikeller** [AlexDisler/cordova-plugin-inapppurchase#111]
Hi guys,

Although the README.md states that:
This function behaves the same as buy() but with subscriptions.

My suggestion is to change the README.md and make it clear:
This function behaves the same as buy() but with subscriptions.
However, please note that subscriptions cannot not be consumed.

Thank you very much.
All the best with the project.

Cheers,
Gui

**Comment by centrual** [comment]
I opened issue about that: https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/124
