### ISSUE TITLE
iOS err=undefined when restorePurchases called

### ISSUE THREAD

**Issue by aesculus** [AlexDisler/cordova-plugin-inapppurchase#116]
Please include:
function is called after onDeviceReady and also tried it in a successful getProducts callback
### Your code / steps to reproduce
	inAppPurchase
	.restorePurchases()
  	.then(function (data) {
			existing_purchases = data;
			var i;
			iap_pro = 0;
			iap_subscription = 0;
			for (i=0; i<existing_purchases.length; i++) {
				if (existing_purchases[i].productId == productIds[1]) {
					if (existing_purchases[i].state = 0) {
						iap_pro = 1;
					}
					window.localStorage.setItem(local_store+"_pro", iap_pro);
				} else {
					if (existing_purchases[i].state = 0) {
						iap_subscription = 1;
					}
					window.localStorage.setItem(local_store+"_subscription", iap_subscription);
				}
			}
			check_iap_status();
			if (interactive) {
				var text = "All purchases have been restored.";
				confirmAction("Restore Purchases", text);
			}
		})
  	.catch(function (err) {
    	confirmAction("Store Error",err.message + " Error=" + err.code);
  	});

### Console output
err.message and err.code are both undefined
### Type of product you are working with consumable/non-consumable/subscription
non consumable
### Version of cordova
PhoneGap (iOS / Android / Windows)
cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
### Version of iOS/Android
10.2.1

**Comment by jersobh** [comment]
if (existing_purchases[i].state = 0) { 
should be
if (existing_purchases[i].state == 0) {

**Comment by jersobh** [comment]
the same for 
if (existing_purchases[i].state = 0) {

**Comment by aesculus** [comment]
Thanks for catching this. I had updated the code that corrected this and forgot to update this issue.

**Comment by jersobh** [comment]
Did it worked? Mine still doesn't work...

**Comment by jersobh** [comment]
Do you really need the getProducts function?

**Comment by jersobh** [comment]
Did you used "com.domain.app.product", or used the getProducts result?

**Comment by aesculus** [comment]
I could never get this to work (maybe because of my = thing), so I moved to a different model for restoring purchases.

I basically set a flag showing I was restoring and then called store.refresh(); again

**Comment by aesculus** [comment]
I used the store.validator and wrote my own routines on a server that checks with both stores.

**Comment by jersobh** [comment]
I really don't want to do this on server side, but it seems that's the only option :(

**Comment by jersobh** [comment]
I'm moving on to https://github.com/j3k0/cordova-plugin-purchase :(
