### ISSUE TITLE
iOS "Confirm" Dialog appears again and again after successful purchase

### ISSUE THREAD

**Issue by nicksmithr** [AlexDisler/cordova-plugin-inapppurchase#118]
Hello,

I've successfully set up for iOS and Android, all is working smooth on Android but on iOS I'm getting an issue both in Sandbox and in Beta. The problem is that after a purchase, the dialog "Confirm your In-App Purchase" comes up again, and asks for the same flow, but of course it has "This In-App purchase has already been bought". Usually it's just twice but sometimes an infinite loop.This is beyond a little problematic, as it looks like the user actually hasn't bought it after the transaction says "successful".

Possibly I've code the code wrong, but since it works fine on Android I'm unsure? 
```

purchaseUnlimited(){
    InAppPurchase
     .getProducts(['productID'])
     .then((products) =>
            InAppPurchase
             .buy('productID')
             .then((products) =>
               console.log(products)
               )
               .then(()  =>
                 this.setUserPurchased()
                 )
             .catch(function (err) {
               alert("ERR: " + JSON.stringify(err.message));
           }))
     .catch(function (err) {
     });
 }
```
XCode Console Output

```
2017-02-21 12:07:44.419449 ...[674:252930] RMStore: products request received response
2017-02-21 12:07:44.419720 ...[674:252930] RMStore: received product with id <productID>
2017-02-21 12:07:44.775275 ...[674:252930] RMStore: products request received response
2017-02-21 12:07:44.775437 ...[674:252930] RMStore: received product with id <productID>v
2017-02-21 12:07:45.890352 ...[674:252930] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
2017-02-21 12:07:46.640080 ...[674:252930] RMStore: products request received response
2017-02-21 12:07:46.640234 ...[674:252930] RMStore: received product with id<productID>
2017-02-21 12:08:12.121504 ...[674:252930] RMStore: transaction purchased with product <productID>
2017-02-21 12:08:12.121866 ...[674:252930] RMStore: WARNING: no receipt verification
2017-02-21 12:08:12.377084 ...[674:252930] RECEIPT INFO...

```
This is with a non-consumable

iOS 10, Cordova 6.5.0

Many thanks in advance,
Nick

**Comment by Seoptics** [comment]
As far as I can see everytime a product is loaded the buy function is called. So if you have 2 IAP products, the dialog for buying will show 2 times. Dont know what the function 'this.setUserPurchased()' is doing, but if that one is calling the 'getproducts', you have the never ending loop.

**Comment by nicksmithr** [comment]
@Seoptics Thanks for your reply, I actually have only one product ID set in the array like 'com.example.product'. And the setUserPurchased does not call any InAppPurchase function, just:

  ```
setUserPurchased(){
    this.storage.set('purchased',true);
    this.userUnlimited=true
    this.navCtrl.push(HomePage)
  }
```

So I'm a little confused with it..!

**Comment by Seoptics** [comment]
Is the page/view maybe reloaded after the purchase somewhere? So the 'getProducts' is called again?

**Comment by nicksmithr** [comment]
Not in my code. I've simplified it all for testing, with one button for "Load" which calls:
```
  load(){
    InAppPurchase
 .getProducts(['com.product.test'])
 .then((products) => {
   console.log(products);
 })
 .catch((err) => {
   console.log(err);
 });
  }
```
And then to buy we have:
```
purchaseUnlimited(){
            InAppPurchase
             .buy('com.focalmark.ul4')
             .then((data) => {
               console.log("fuckfuck")
               this.setUserPurchased()

               })
             .catch(function (err) {
               alert("ERR: " + JSON.stringify(err.message));
           })
 }

```

And finally to this.setUserPurchased():

```
  setUserPurchased(){
    console.log("Purchased.")
  }

```

And the problem is still happening, it's still coming up at the end of the purchase again.

**Comment by nicksmithr** [comment]
The `load` seems to be calling the product twice, which is strange, I only have one product in iTunes Connect.
```

017-02-21 12:47:04.469381 ...[739:264873] RMStore: products request received response
2017-02-21 12:47:04.469788 ...[739:264873] RMStore: received product with id ...
2017-02-21 12:47:04.498151 ...[739:264873] [{"productId":"com....","title":"com....","description":"com.....4","price":"£0.99"}]
```

**Comment by Seoptics** [comment]
This code is different then the one in your original code, there you have the .buy() in your .then() of your .getProducts() function. But that still doesn't explain the unlimited loop....

**Comment by nicksmithr** [comment]
Yeah, I'm trying different things to try and remove that loop, the load button should simplify things. I think the problem is that the "getProducts" is returning the same product twice. Hence, on the "buy" it has two products in the buy, but should only have one as there's only one product ID.

**Comment by nicksmithr** [comment]
Seems to be an issue with Ionic framework firing (click) event twice. Sorry for that. Thanks for your time @Seoptics !

**Comment by Seoptics** [comment]
np, I'am having still lots of issues with the IAP... hope someday I can solve them too

**Comment by nicksmithr** [comment]
# #
