### ISSUE TITLE
Hi Alex,  i am having issue please advice me. thanks in advance.

### ISSUE THREAD

**Issue by globalizeme** [AlexDisler/cordova-plugin-inapppurchase#121]
![screenshot_2017-03-01-19-21-52-472_com android vending](https://cloud.githubusercontent.com/assets/14217852/23462694/d37c97d6-feb4-11e6-9772-bb785a869134.png)
Please include:

### Your code / steps to reproduce
```js

```

**Comment by Seoptics** [comment]
You need to be logged in as the message is saying to contact the Google Play store. This could be your own account or a alpha/beta test account.

**Comment by Cipri** [comment]
Make sure the product is active.
