### ISSUE TITLE
IOS - No products found

### ISSUE THREAD

**Issue by Doomic** [AlexDisler/cordova-plugin-inapppurchase#122]
I have used your plugin succesfull for android. but can't get it working for ios.
not sure if it is a plugin related issue or ios issue.

I have made a test product (first i tried it with a subscription, but just for traking the issue i made a product). Called the name and id the same to be 100% sure it will find it by the name/id. (read somewhere that someone needed to use the name instead of the id to buy a product).

i build the code below to my ipad. (both calls (getProducts and the buy) are surrounded by ng-click (button press) performed functions). But i get an empty array or error back. 
Somehow it can't find the products!

Any suggestion where to look to fix this?
The app is still in development so there is no production submission done at the moment. But i believe that isn't nessesery. Also tried to make a distribution build, but the issue remains.

![image](https://cloud.githubusercontent.com/assets/457752/23504671/d2bc74ba-ff40-11e6-89c3-6306ad822525.png)

```
inAppPurchase
	.getProducts(["testpurchase"])
	.then(function(products) {
		console.log(products); //[]
	});
inAppPurchase
	.buy("testpurchase")
	.then(function(data) {
		console.log(products);
	})
	.catch(function(err) {
		console.log(err); //{errorMessage: "Unknown product identifier", errorCode: 100}
	});

```

**Comment by Doomic** [comment]
No idea what i changed.. but somehow it works now... my gues is some of the changes on the ios develepor site has finaly have been submitted. This issue can be closed.

**Comment by epetre** [comment]
Experiencing the same issue on my side, maybe something needs to be approved... I'm not sure what to do and apple's documentation is not clear about if the product needs any sort of approval before being available in the sandbox.
