### ISSUE TITLE
format of the play_store_key

### ISSUE THREAD

**Issue by speedfl** [AlexDisler/cordova-plugin-inapppurchase#125]
First thanks for your plugin

I just would like to know the format of the play_store_key

In fact I have something lilke

123456789-123abc456df7f8f78f54f.apps.googleusercontent.com

I would like to know if I have to put with or without the .apps.googleusercontent.com

Thanks a lot

**Comment by centrual** [comment]
1) Open Google Play Developer Console
2) Press All Applications
3) Press your app's name.
4) Press Services and API
5) Copy the base64 license key code

It's like: `MIIBIjANBgkqhkiG9w045QEFAAOCAQ8AMIIBCgKCAQEA3YOiUBpxSR0P8zjS8V6n3flNhDb2pSpivCaMEcQCg5xipe4bh5gc5djGxZSnFBmmN8N/YOf0yBwzkNeM233B1EQMBV5CZIHwfEcKcBHdP2rPjwVSrwGff+pTLldBHlkWXoEFyTpVnbQ6RdWsydiKL5cXnAZ1Fyt1GddsruvyviJvZYVuGVI+MYWDQOFPw13ULfjd4xUs3WObilUYajrH9Cg6Hf2mAVnuIhDsUlqolSWmqi6TlLoK1M+hp1XylwoZ8G05ZskjoMwUesh48tM7dn0nhz9ePQTctpGqLCIzmvtHvKcGbv64FtD8jsoWvyhrKScXhJh1Ro+7GfHnH3+mPwIDAQAB`

**Comment by speedfl** [comment]
Thanks a lot!

You can close the issue :)
