### ISSUE TITLE
Is plugin abandoned?

### ISSUE THREAD

**Issue by centrual** [AlexDisler/cordova-plugin-inapppurchase#126]
@AlexDisler not contributing anymore. Last blog post from him at 30 Apr 2016 and last contribution at 29 December 2016 ( very rare ).

He has not been seen for 3 months. Has he left the project?

Any information about that?

**Comment by speedfl** [comment]
It seems.
There are lot of issues unresolved or resolved with advice but not close.
As well there are lot of unmerged pr.
It is sad because really usefull. Really mandatory for ionic apps.
As it is MIT Liscence someone should take the hand. 
We should see with ionic team itself maybe...

**Comment by AlexDisler** [comment]
Sorry, didn't have much time to work on it recently. Yeah please feel free to fork it.

**Comment by speedfl** [comment]
Alex you are alive !!!!!!! 
Thanks god !!! 
I am joking.  I understand. We all have our jobs and life.
But fortunately you are still there for tricky question.
As I said this plugin is one of the most important for ionic project. So it must not die.
Have a nice day.

**Comment by cmorbitzer** [comment]
Forked at https://github.com/cmorbitzer/cordova-plugin-inapppurchase
Will do some maintenance on the repo soon. Feel free to submit PRs and new issues there
