### ISSUE TITLE
Plugin don't ask user when list products

### ISSUE THREAD

**Issue by jrmessias** [AlexDisler/cordova-plugin-inapppurchase#128]
Hi,

I try use this plugin in iOS and have some problems.

When I get products, the iOS don't ask me a user account (need use sandbox for test) so can't get the products with IDs.

### Console output
RMStore: products request received response
RMStore: invalid product with id xx.xxx.xxxxxxx

The product is non-consumable

Version of cordova: 6.5.0

Version of iOS: 10.2.1

**Comment by petrot** [comment]
Go to iTunes  connect and fill your billing and tax info under Agreements, Tax, and Banking menu.

**Comment by jrmessias** [comment]
Thank you @petrot
