### ISSUE TITLE
iOS: Add method getAppReceipt 

### ISSUE THREAD

**Issue by kristfal** [AlexDisler/cordova-plugin-inapppurchase#13]
In order to validate a restored purchase, the full receipt is required. On iOS, the receipt is not returned when calling:

```
window.inAppPurchase.restorePurchases().then(function(data) {
			console.log(data);
		});
```

A super easy hack is to add the transactionReceipt to the returned in the obj-C side:

```
 [validTransactions addObject:@{
                                 @"productId": NILABLE(transaction.payment.productIdentifier),
                                 @"date": NILABLE(transactionDateString),
                                 @"transactionId": NILABLE(transaction.transactionIdentifier),
                                 @"transactionReceipt": NILABLE([[transaction transactionReceipt] base64EncodedStringWithOptions:0])
                                 }];
```

however, this has been deprecated since iOS7 and we should rather [refresh the receipt](https://github.com/robotmedia/RMStore#refresh-receipt-ios-7-only) and then get the App receipt.

**Comment by AlexDisler** [comment]
The receipt is returned by the [buy()](https://github.com/AlexDisler/cordova-plugin-inapppurchase#buy) function (without using TransactionReceipt)

See https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/2#issuecomment-197067550

**Comment by kristfal** [comment]
@AlexDisler true, but how would you recommend implementing a restore method/button (as required by Apple) that restores all existing purchases? The typical use case would be when a user for switches devices.

**Comment by AlexDisler** [comment]
Ah I see. Yeah you're right, there's no receipt for restored purchases.

There should be a ```refreshReceipt()``` function to get the updated receipt. Or even better, ```restorePurchases()``` can refresh the receipt and return it so it will work the same as it is on Android.

It should be easy to add since RMStore already does this: https://github.com/robotmedia/RMStore#refresh-receipt-ios-7-only
