### ISSUE TITLE
I buy the product but I can not buy it the second time.

### ISSUE THREAD

**Issue by zafercelik** [AlexDisler/cordova-plugin-inapppurchase#131]
Please include:
I buy the product but I can not buy it the second time.

I use devextreme;

### Your code / steps to reproduce
```js
 inAppPurchase
      .buy(urunID)
      .then(function (data) {
        return inAppPurchase.consume(data.type, data.receipt, data.signature);
      })
      .then(function () {
        alert("Satın alma Başarılı");
      })
      .catch(function (err) {
        alert("Başarısız! "+ err);
      });
```

**Comment by centrual** [comment]
Merhaba Zafer,

İkinci defa satın almaya çalıştığında ortaya çıkan problemi açıklar mısın?

English:
Hello Zafer,

Can you describe what happening on second buy attempt?

**Comment by moritzgloeckl** [comment]
You need to consume the product first, if you want to buy it again.

**Comment by yeldarby** [comment]
@moritzgloeckl - I do. But it doesn’t appear to be working on android.

**Comment by moritzgloeckl** [comment]
@yeldarby Please open another ticket.
