### ISSUE TITLE
Receipts on DB

### ISSUE THREAD

**Issue by dedieudiego** [AlexDisler/cordova-plugin-inapppurchase#132]
At the end of this text (https://alexdisler.com/2016/03/20/validating-cordova-in-app-purchases-on-ios-and-android-using-nodejs/) says _"You also must check that the receipt does not already exist in your database. The same receipt can be validated an unlimited number of times and be valid."_

Why I should check if the receipt already exists?
If does exists, what does that mean? Is a fake purchase? I should reject it?

**Comment by palbaladejo** [comment]
Yes. You have to check if the purchase is already consumed, for example.

https://developers.google.com/android-publisher/api-ref/purchases/products
