### ISSUE TITLE
Feature request: Chinese app stores

### ISSUE THREAD

**Issue by afeezaziz** [AlexDisler/cordova-plugin-inapppurchase#133]
Hi, 

Right now only iOS(Apple App Store) and Google Play are supported. There are a few of famous app stores in China for Android but not Google Play. 

How can I use the plugin with these chinese app stores? If there is no way right now, can this be a feature?

**Comment by moritzgloeckl** [comment]
Hi,

you can fork the project and try to come up with a solution yourself and then send us a pull request. But this feature is not planned yet.

Thanks!
