### ISSUE TITLE
Item can't be consumed error

### ISSUE THREAD

**Issue by daniel7558** [AlexDisler/cordova-plugin-inapppurchase#14]
Hi, 
I cannot consume items and trying so produces an consumption error.

Code:
```
inAppPurchase
    .buy("test_6")
    .then(function (data) {
        alert("BUY: " + JSON.stringify(data));
        return inAppPurchase.consume(data.productId, data.receipt, data.signature);
    })
    .then(function () {
        credit.addCredit(credit_amount); // deliver goods
        alert('OK');
    })
    .catch(function (err) {

        alert("ERR: " + JSON.stringify(err));
    });
```

Please note that I'm passing data.productId to the consume function as data.productType does not exist. Guess it is an error in the example code.

I attached both alerts:
![buy](https://cloud.githubusercontent.com/assets/2155063/14183144/e7288f04-f76e-11e5-971d-0c38ab3444ea.png)
![err](https://cloud.githubusercontent.com/assets/2155063/14183145/e72a5938-f76e-11e5-995c-1e875366c6c9.png)

The item is a managed item and not a subscription so it should be consumable. 
When I run   ```inAppPurchase.restorePurchases()``` it lists the item so I guess the buying process did complete successful and the product is owned by the user.

Cordova: 6.1.0
Android: 5.0

Best regards, 
Daniel

**Comment by AlexDisler** [comment]
Hi,
Try passing ```data.type``` as the first param.

**Comment by daniel7558** [comment]
Hi, 
with ```inAppPurchase.consume(data.type, data.receipt, data.signature);``` an empty object is passed to the ```.catch```

**Comment by daniel7558** [comment]
Sorry. It works fine now. 
Dependency for my credit function was missing so it created an error :) 

Thanks, data.type solved it :+1:
