### ISSUE TITLE
Cannot connect to iTunes Store

### ISSUE THREAD

**Issue by priyag676** [AlexDisler/cordova-plugin-inapppurchase#146]
Please include:

Getting error SKErrorDomain Code=0 "Cannot connect to iTunes Store" when calling window.inAppPurchase.restorePurchases() in sandbox mode and Test Flight

```js
window.inAppPurchase.restorePurchases().then(function (response) {
console.log(response)
 }).catch(function (error) {
console.log(error);
  deferred.reject(error);
 });

```
### Console output
RMStore: restored transactions failed with error Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}

### Version of cordova
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.3.0

local packages:

    @ionic/cli-plugin-cordova : 1.3.0
    @ionic/cli-plugin-ionic1  : 1.3.0
    Cordova Platforms         : android 6.1.2 ios 4.3.1
    Ionic Framework           : ionic1 1.3.2

### Version of iOS/Android
System:
    Node       : v7.0.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.1 Build version 8B62
    ios-deploy : 1.9.0
    ios-sim    : 5.0.12

@AlexDisler

**Comment by betatools** [comment]
This happened to me when I was logged in on the device with a user without sandbox access. 

Could that be the issue?

**Comment by PrithiviRajG** [comment]
I am also facing the same issue. 

@priyag676 did you find the solution?

**Comment by olaferlandsen** [comment]
I resolve It with the itunes Connect contracts(bank and taxs).

**Comment by PrithiviRajG** [comment]
@olaferlandsen did you able to test the inApp purchase in IOS simulator?

In IOS simulator with sandbox environment, getProducts() is working fine but restorePurchase() and buy() method is not working and I am getting exception like 'cannot connect to iTunes store'. I am using IOS version 10.3.1

**Comment by moritzgloeckl** [comment]
@PrithiviRajG Seems like it's not working in an iOS Simulator:

https://stackoverflow.com/questions/26246749/can-in-app-purchases-be-tested-in-the-ios-8-xcode-6-simulator

> As of 2015-04-20, I am unable to get IAP to work in the Xcode 6.3 simulator. Code works on the device, but the simulator always returns SKErrorDomain Code=0 "Cannot connect to iTunes Store"

**Comment by olaferlandsen** [comment]
No, I try with a real device

**Comment by moritzgloeckl** [comment]
@olaferlandsen ... and that's probably the reason it works for you.

**Comment by olaferlandsen** [comment]
Yesenia, cos' IAP api don't work with simulators.
Please read here:

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/iOS_Simulator_Guide/TestingontheiOSSimulator/TestingontheiOSSimulator.html#//apple_ref/doc/uid/TP40012848-CH4-SW1
