### ISSUE TITLE
Google Play Store “Error [DF-AA-09]” on purchase

### ISSUE THREAD

**Issue by expouic** [AlexDisler/cordova-plugin-inapppurchase#147]
When try to purchase any item have the error message from Google 
“Error retrieving information from server [DF-AA-09]”

Anyone know what this error means and how to solve?

**Comment by moritzgloeckl** [comment]
Refer to [this StackOverflow Answer](https://stackoverflow.com/questions/44484061/google-play-store-error-retrieving-information-from-server-df-aa-09-on-purch).
