### ISSUE TITLE
How to revoke the completed inapp Test purchase

### ISSUE THREAD

**Issue by PrithiviRajG** [AlexDisler/cordova-plugin-inapppurchase#152]
Hello Team,

I wanted to revoke my completed inapp Test purchase manually so I can continue to test the App with my same account. Thanks.

**Comment by CesarRubenAlejandro** [comment]
Same problem here,
you can check https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/55 
The correct way is to perform a Consume request after you purchase. However, if you didn't (like me) you will have to wait the default time for the Order to be consumed in your google play test account.
I've contacted Google but they were not able to help me yet.

If you come up with a solution please advice.

**Comment by webster76** [comment]
Had the same problem but I think I found a way. If you have Android Studio installed on your development machine, you have to find the executable file **adb**
Connect your device or start your emulator, but be sure to have only one device running. Then call this command (in my case on Windows):
`C:\Users\<your-username>\AppData\Local\Android\sdk\platform-tools>**adb.exe shell pm clear com.android.vending**`

As an alternative, you can open up the Dev-Tools on chrome while running your app in debug-mode. In the console, do this one:
`inAppPurchase.restorePurchases()
    .then(function (purchases) {
        console.warn(purchases);
    });`

Right click the logged purchase that you want to "delete" and choose "store as global variable" (temp1), then call
`inAppPurchase.consume(temp1.productType, temp1.receipt, temp1.signature);`

Now you should be able to buy the product again on the same account.

**Comment by AngelaRg** [comment]
@webster76
 
Hi! I tried your second solution but by doing

> inAppPurchase.restorePurchases().then(function (purchases) {console.warn(purchases); });

it returns these errors:

> t {__zone_symbol__state: null, __zone_symbol__value: Array(0)}

> polyfills.js:3 Unhandled Promise rejection: Error retrieving purchase details ; Zone: <root> ; Task: Promise.then ; Value: Error retrieving purchase details undefined

> polyfills.js:3 Error: Uncaught (in promise): Error retrieving purchase details

Any ideas? I'll keep trying..

**Comment by webster76** [comment]
@AngelaRg Perhaps one of these:

- logged out from google account
- no internet connection

My test google accounts were blocked after a few test purchases and i had to verify that it's mine by entering my phone number.

What about the other solution?

**Comment by AngelaRg** [comment]
Just FYI, seems that the error only happens when I use this method with a tester account. (Which is what I need) And the account doesn't seem to be blocked, looks perfectly logged in.

On the other side, on my personal phone (with no tester account) i am able to run the app and execute these commands on the Dev Tools console. So it really seems to be a problem with the tester account.

@webster76  I´ll try the android studio solution, hope that works.

**Comment by AngelaRg** [comment]
@webster76  I didn't have android studio on my machine before but i gave it a try and downloaded it (had to reconfigure paths and all that).. then i did successfully the command you mentioned but my product seems to be still consumed .. is there anything else i sholud check besides doing the command? or is it not working because i didn´t had it at the time of the purchase?

Can you explain me what that command does? I'm unfamiliar to that

**Comment by webster76** [comment]
@AngelaRg afaik the adb command clears the playstore cache on the actual connected device.
Is your in-app-product of type "managed" or "subscribable"? Subscribables can not be consumed.
The consuming works with a tester (added to licensed testing in play console settings) and a regular account on my side. Btw: the test-account must not be the same account as the developer account.

**Comment by AngelaRg** [comment]
@webster76 yeah, it is a managed product. and i don't see anything missing, might try again. Thanks

**Comment by AngelaRg** [comment]
@webster76  you're right. I had deleted the account as tester on Developer Console. My bad, that might have been the problem. Now that i added it back, the command works.

Although clearing the cache isn't the same as consuming the product, is it? Now I get the product the first time I enter my store after doing the adb command, but if i keep navigating or close the app and go back to the store, i don´t get my product shown... as if it is still not consumed.

Anyway, at least this solution lets me test a little more. Thanks 👍

**Comment by moritzgloeckl** [comment]
I'm closing this now.
