### ISSUE TITLE
inAppPurchase is not defined.

### ISSUE THREAD

**Issue by edoko** [AlexDisler/cordova-plugin-inapppurchase#155]
Please include:

### Your code / steps to reproduce
```js

inapp.js


function loadProducts() {
      inAppPurchase
      .getProducts(cookie_1) // productid is 'cookie_1'
      .then(function (products) {
        console.log(products);
        alert("success");
      })
      .catch(function (err) {
        console.log(err);
        alert("fail");
      });
}

function buy(productId) {
      inAppPurchase
      .buy(productId)
      .then(function (data) {
        console.log(JSON.stringify(data));
        console.log('consuming transactionId: ' + data.transactionId);
        return inAppPurchase.consume(data.type, data.receipt, data.signature);
      })
      .then(function () {
        console.log('consume done!');
        alert("success");
      })
      .catch(function (err) {
        console.log(err);
        alert("fail");
      });
    }


```

```html
<script type='text/javascript' src="js/inapp.js"></script>


<a href="javascript: loadProducts();" class="btn_purchase">get</a>
<a href="javascript: buy(product.productId);" class="btn_purchase_2">buy</a>

```

### Console output

inAppPurchase is not defined", source: file:///android_asset/www/js/inapp.js (2)

### Type of product you are working with consumable/non-consumable/subscription

consumable(item)

### Version of cordova

cordova 7.0.1

### Version of iOS/Android

Android 7.0 (Galaxy S8)

I don't use ionic framework, only html/css/javascript.

but, it occurs error.

How use it ? i'm so sorry, I don't english well.

**Comment by edoko** [comment]
umm.. I fix error.. but btn_purchase_2 occurs another error.

console output :
[INFO:CONSOLE(5)] "[object Object]", source: file:///android_asset/www/js/inapp.js (5)
[INFO:CONSOLE(1)] "Uncaught ReferenceError: product is not defined", source:  (1)

**Comment by moritzgloeckl** [comment]
Hi,

The `.getProducts()` method expects an array of product ids. As far as I can tell you're providing a string:

`.getProducts(cookie_1) // productid is 'cookie_1'`

It should look like this:

`.getProducts(["cookie_1"])`

**Comment by tonoanzzu** [comment]
Hello, how did you implement the plugin, I also want to use html/css /javascript only
