### ISSUE TITLE
Why App title is added to product title?

### ISSUE THREAD

**Issue by ColDrekken** [AlexDisler/cordova-plugin-inapppurchase#157]
Hello,

i got something strange which not really seems like a bug. 
I get the products from GooglePlay without any problems but is there a idea why it adds my app title in  round brackets behind my product title? 

For example:

[{"productId":"tv.mobiletrading.basechat.inappbilling.15minutestop","title":"15 Minuten (Base Chat - Quatschen, Flirten, Freunde finden)","description":"15 Minuten on Top in Shuffle","price":"3,99 €"}

title in Playstore console is only "15Minutes" 

any idea?

thx in advanced

**Comment by moritzgloeckl** [comment]
Hi,

we can't control what the in app payment popup is showing, this is up to Google to decide, and they decided that they are showing the app title behind the product title. Nothing we can do about this.

![image](https://user-images.githubusercontent.com/1828337/29202678-e6d33b10-7e6a-11e7-94a9-eb0c7a66aa0b.png)
