### ISSUE TITLE
Android receipt is missing autoRenewing property for subscriptions

### ISSUE THREAD

**Issue by kristfal** [AlexDisler/cordova-plugin-inapppurchase#16]
For subscription receipt validation, the android validation API requires an autoRenewing property. It should be returned along with the rest of the receipt. 

A cheap workaround is now to force it to be true before sending the receipt for validation.

Code:

```js

window.inAppPurchase.restorePurchases().then((data) => {
  for (let product of data) {
     console.log(JSON.parse(product.receipt))
  }
});
```

Result:

```
[{
  "orderId": "",
  "packageName": "package",
  "productId": "Id",
  "purchaseTime": 1457082302891,
  "purchaseState": 0,
  "purchaseToken": "phfkmbjoipmleimohnnedalg.AO-J1OwD9WMKn2tl....7Xm"
},
(...)
]
```

Expected result:

```
[{
  "orderId": "",
  "packageName": "package",
  "productId": "Id",
  "purchaseTime": 1457082302891,
  "purchaseState": 0,
  "purchaseToken": "phfkmbjoipmleimohnnedalg.AO-J1OwD9WMKn2tl....7Xm",
  "autoRenewing": true
},
(...)
]
```

Type of product you are working with consumable/non-consumable/subscription:

Android subscription

**Comment by AlexDisler** [comment]
Hey, can you please confirm it's fixed (based on master, not released to npm yet)

**Comment by kristfal** [comment]
@AlexDisler Works like a charm. Thanks Alex.

Just got to give you credit for fast turnarounds and creating by far the best IAP plugin available for Cordova. Stellar work.

**Comment by AlexDisler** [comment]
Thank you
