### ISSUE TITLE
Refund issues

### ISSUE THREAD

**Issue by ievhenganchin** [AlexDisler/cordova-plugin-inapppurchase#160]
Hi,

I found some strange caching from google side while refunding non-consumable products:

- buy product (app in alpha release) using valid card information
- you card will be charged
- this new product will be returned in restorePurchases() with state == 0
- go to dev console and refund this order
- money are returned to your credit card
- but restorePurchases() still returning this product with state == 0

To fix this I need to do one of the following actions:
- reinstall app
- force stop of "Play Store" app

Is there any ways to clear this cache in elegant way? So I can clear it from app somehow.

**Comment by moritzgloeckl** [comment]
Hi there,

I think this behaviour is normal. The Google In-App Library caches the product state. There's a very well written answer to this on SO [check it out](https://stackoverflow.com/questions/15762370/does-google-play-in-app-billing-version-3-support-refunds/15821320#15821320).
