### ISSUE TITLE
inAppPurchase undefined error in iOS, android is working fine

### ISSUE THREAD

**Issue by shivenigma** [AlexDisler/cordova-plugin-inapppurchase#165]
Please include:

### Your code / steps to reproduce
```js
$ionicPlatform.ready(function () {
            inAppPurchase
                .getProducts(
                    [
                        'ids'
                    ])
                .then(function (products) {
                    ref.inApp = products;
                    console.log(products);
                })
                .catch(function (err) {
                    console.log(err);
                });
        });
```
### Console output
inApp purchase is undefined
### Type of product you are working with consumable/non-consumable/subscription
consumable
### Version of cordova
cordova -v = 7.0.1
### Version of iOS/Android
ios 4.4.0

**Comment by shivenigma** [comment]
what could be the problem? I didn't added this as a dependency to angularJS becuase I know this is a global object. Do I need to link any file in index.html. I didn't see anything there like this. Please help me.

**Comment by moritzgloeckl** [comment]
How did you install the library?

**Comment by shivenigma** [comment]
using the cordova CLI `cordova plugin add cordova-plugin-inapppurchase`, and I forgot to mention this is an ionic project if that makes any difference.

**Comment by moritzgloeckl** [comment]
Can you paste the output of `cordova plugin list`

**Comment by shivenigma** [comment]
vigneshm$ cordova plugin ls

card.io.cordova.mobilesdk 2.0.1 "CardIO"
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
com.paypal.cordova.mobilesdk 3.2.0 "PayPalMobile"
cordova-plugin-calendar 4.5.1 "Calendar"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-media-capture 1.4.0 "Capture"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 2.0.0 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
cordova-plugin-x-toast 2.5.0 "Toast"
ionic-plugin-keyboard 2.2.0 "Keyboard"
phonegap-plugin-push 1.8.1 "PushPlugin"

**Comment by shivenigma** [comment]
Never mind, removing and reinstalling iOS platform made it work. Sorry for the noob issue. Thanks for your time @moritzgloeckl . Closing this issues as it is not a valid one.
