### ISSUE TITLE
getProducts is returning TypeError

### ISSUE THREAD

**Issue by TQTNguyen** [AlexDisler/cordova-plugin-inapppurchase#166]
Please include:

### Your code / steps to reproduce
```js
function loadProd()
{
    var id = ['android.test.purchased'];

    inAppPurchase
      .getProducts(id)
      .then(function (products) {
          console.log(products);
      })
      .catch(function (err) {
          console.log(err);
      });
}
```
My login page calls loadProd() before logging the user in, but the error occurs on calling function.

### Console output
TypeError: Cannot read property 'code' of null

### Type of product you are working with consumable/non-consumable/subscription
Subscription
### Version of cordova
6.5.0
### Version of iOS/Android
Android 4.4.4

**Comment by moritzgloeckl** [comment]
Hi,

please include the full Console Output (which file, line, etc.)

Thank you.

**Comment by TQTNguyen** [comment]
Error in Error callbackId: InAppBillingV3183932304 : TypeError: Cannot read property 'code' of null
cordova.js (312,47)

**Comment by jhpassion0621** [comment]
I am getting Same error
