### ISSUE TITLE
inAppPurchase not defined

### ISSUE THREAD

**Issue by UooVeee** [AlexDisler/cordova-plugin-inapppurchase#17]
I added the plugin using **cordova plugin add cordova-plugin-inapppurchase ** in my project.

Then I added following code in one of the controller : 

 angular.module('app.controllers')
    .controller('createPlanController', ['$scope', '$state', 'StorageService', 'NetworkService', 'AppConstant', 'AlertService', 'RouterService', '$rootScope', function ($scope, $state, StorageService, NetworkService, AppConstant, AlertService, RouterService, $rootScope) {
$scope.loadProducts = function () {
    // $ionicLoading.show({ template: spinner + 'Loading Products...' });
    if(inAppPurchase == 'undefined')
      alert ("inapp not available");

      inAppPurchase
      .getProducts(productIds)
      .then(function (products) {
        
        alert("got products")
        $scope.products = products;
      })
      .catch(function (err) {
        
        alert(err);
      });
      };
}

Installed platforms: android 5.1.1, ios 4.0.1

This is giving me inAppPurchase not defined. Am I doing something wrong?

**Comment by dougflip** [comment]
@UooVeee is this deployed to the device or are you testing in the browser?

**Comment by UooVeee** [comment]
@dougflip I am trying this on emulator via xcode

**Comment by dougflip** [comment]
Ah ok - not sure about the emulator. I know that it isn't defined when running in the browser. I have a small wrapper in my code to check if the plugin is defined and return a stub when it is not.

**Comment by AlexDisler** [comment]
Try running ```cordova plugin list```, was the plugin was successfully installed?

Which cordova version are you using?

**Comment by alamops** [comment]
You are using Ionic, put the plugin call in the $ionicPlatform.ready(function () {}); or call $timeout();

**Comment by AlexDisler** [comment]
@UooVeee If you still have this issue, please re-open with more details

**Comment by patrickhofer** [comment]
I'm facing the same issue. 

Installed like in the example. 

This is my code: 
```
controller('StartCtrl', function($scope, $state, $http, $timeout, $ionicLoading, $ionicPlatform) {


    $scope.unlocked_s = 'false';

$ionicPlatform.ready(function () {

    var productIds = ["ch.tapsy.colosseo"];

      var spinner = '<ion-spinner icon="dots" class="spinner-stable"></ion-spinner><br/>';

      $scope.loadProducts = function() {

        $ionicLoading.show({
          template: spinner + 'Loading Products...'
        });
        inAppPurchase
          .getProducts(productIds)
          .then(function(products) {
            $ionicLoading.hide();
            $scope.products = products;
          })
          .catch(function(err) {
            $ionicLoading.hide();
            console.log(err);
          });
      };


      $scope.buy = function(productId) {

        $ionicLoading.show({
          template: spinner + 'Choufe...'
        });
        inAppPurchase
          .buy(productId)
          .then(function(data) {
            console.log(JSON.stringify(data));
            console.log('consuming transactionId: ' + data.transactionId);
            return inAppPurchase.consume(data.type, data.receipt, data.signature);
          })
          .then(function() {
            localStorage.setItem('sold', 'true');
            $ionicLoading.hide();
              $state.go("12")
          })
          .catch(function(err) {
            $ionicLoading.hide();
            console.log(err);
            $ionicPopup.alert({
              title: 'Something went wrong',
              template: 'Check your console log for the error details'
            });
          });

      };

      $scope.restore = function() {
        $ionicLoading.show({
          template: spinner + 'Restoring Purchases...'
        });
        inAppPurchase
          .restorePurchases()
          .then(function(purchases) {
            $ionicLoading.hide();
            console.log(JSON.stringify(purchases));
            $ionicPopup.alert({
              title: 'Restore was successful!',
              template: 'Check your console log for the restored purchases data'
            });
            localStorage.setItem('sold', 'true');
          })
          .catch(function(err) {
            $ionicLoading.hide();
            console.log(err);
            $ionicPopup.alert({
              title: 'Something went wrong',
              template: 'Check your console log for the error details'
            });
          });
      };

      });
      $scope.checkls = function() {
        var getelem = localStorage.getItem('sold');
        if (getelem != "true") {
          $state.go("home");
        }
        if (getelem == "true") {
          $state.go("unlocked");
        }
      }
```

**Comment by vance** [comment]
This will not work in an emulator since you have to be authenticated as a valid itunes user.

**Comment by hamzaadad** [comment]
running on real device, still got "inAppBrowser is not defined" even if i compile the app (android) with no erros, plugin is in cordova plugin list... please anyhelp ?

Cordova android@6.2.2

**Comment by Langerz82** [comment]
I got the same issue hamzaadad.

Cordova@8.0.0
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"

edit: think I found the issue I was misssing cordova.js script from the index.html.

**Comment by taoakasa** [comment]
Answered by wasa4587 https://github.com/wasa4587 

this occurs because the app loads first than the plugin, try this
setTimeout(function() {    
    loadProducts  ()
    }, 5000);

It's a common issue among ionic/cordova plugins
