### ISSUE TITLE
iOS - inAppPurchase throws error

### ISSUE THREAD

**Issue by Walgermo** [AlexDisler/cordova-plugin-inapppurchase#174]
Hi,

My in app purchase on iOS throws an error. 
Works as expected on Android. 

Any ideas? 😄 

### Code
`this.inAppPurchase
          .buy(this.productId)
          .then(data => {
            this.inAppPurchase.consume(data.productType, data.receipt, data.signature);
          })
          .then(() => {
            // firebase
            this.meets.push({
              name: this.name,
              responsible: this.responsible,
              phone: this.phone,
              email: this.email,
              sport: this.sport,
              created: date,
              createdNeg: dateNeg,
              password: this.password,
              participants: participantsToNumber
            });
            this.sendMail();
            this.dismiss();
          })
          .catch(error => {
            const errorMsg = JSON.stringify(error);
            this.presentAlert('The error has been logged and will be fixed as soon as possible!');
            this.sendMailError(errorMsg);
          });
`

### Console output
`{"line":84,"column":23,"sourceURL":"http://localhost:8080/var/containers/Bundle/Application/840D764D-BF16-4BB6-9D7D-A39CE8A3B98F/Referees.app/www/plugins/cordova-plugin-inapppurchase/www/index-ios.js","__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}} `

### Type of product you are working with consumable/non-consumable/subscription
consumable.

### Version of cordova
Latest.

### Version of iOS/Android
Latest.

**Comment by moritzgloeckl** [comment]
Hi there,

can you please add a normal javascript console stack trace of the error? It's a bit hard to understand which error it is and where it's exactly coming from. 

Thanks!

**Comment by moritzgloeckl** [comment]
Ok by looking at your properly formatted code I can see the problem:

    this.inAppPurchase
          .buy(this.productId)
          .then(data => {
            this.inAppPurchase.consume(data.productType, data.receipt, data.signature);
          })
          .then(() => {

See, you're calling `.then()` twice. That won't work. You probably want to add the then after you `.consume()`

**Comment by Walgermo** [comment]
Yes, thats right @moritzgloeckl. Ok, i tought it was possible to stack as many .then() as i wanted. 
I will try to add .then() on the consume() instead. 

Thanks for the quick reply! 👍

**Comment by jayeshkorat18** [comment]
Hi

My in-app purchase on iOS throws an error in below case.
I have 3 plan of auto-renewing subscription
1) Individual plan-$19
2)Team plan-$99
3)Bussiness plan-$199

My current plan is "Individual". When I try an upgrade plan to "Team or business" than a system gives a message your plan subscribe successfully. but in response getting an error **"{"errorMessage":"Cannot connect to iTunes Store","errorCode":0}"**

I am using ionic 3 with following method
this.iap
      .subscribe(this.productName)
      .then((data) => {
      console.log("success")
      }).catch((error) => {
      console.log("error")
      });

When I downgrad plan like "team" to "individual" is working fine.
Please let me know what is the issue.
