### ISSUE TITLE
Payment is successful. But product is not active without reopening the app.

### ISSUE THREAD

**Issue by momikus** [AlexDisler/cordova-plugin-inapppurchase#176]
When a user buys our inapp product (android), payment is done without an issue. But the user's paid product is not active till closing and openin the app again. It was working totally correct before. We did not change our code. Our product is: "Remove Ads".

### Console output
code: -6
errorCode: -6
message: "Could not complete purchase"
response: -1008
text: "IAB returned null purchaseData or dataSignature (response: -1008:Unknown error)"

### My code
```js
inAppPurchase
.subscribe(purcahaseID)
.then(function(data) {
    return inAppPurchase.consume(data.type, data.receipt, data.signature);
}).then(function () {
    purchased(purcahaseID); // our function to remove ads (does not triggering now)
});
```

**Comment by moritzgloeckl** [comment]
You're mixing up the promises. You can't call `.then` twice. The second `.then` needs to be called on the `.consume`.

**Comment by momikus** [comment]
Could you please give an example?

**Comment by moritzgloeckl** [comment]
```js
inAppPurchase
.subscribe(purcahaseID)
.then(function(data) {
    inAppPurchase.consume(data.type, data.receipt, data.signature)
    .then(function () {
        purchased(purcahaseID);
    });
});
```

**Comment by faytekin** [comment]
I have a product with type: managed product. This product is for removing ads. I get the same error with this  code block.

**Comment by faytekin** [comment]
Okey I fixed.
