### ISSUE TITLE
iOS 11 white screen

### ISSUE THREAD

**Issue by Allan-Nava** [AlexDisler/cordova-plugin-inapppurchase#177]
Hi,

I'm getting the white screen on iOS

### Your code / steps to reproduce
```
$scope.showBuy = function(){
		$ionicModal.fromTemplateUrl('modal-buy.html', {
			scope: $scope,
			animation: 'slide-in-up'
		}).then(function(modal) {
			inAppPurchase
			.getProducts(productIds)
			.then(function (products) {
			$scope.products = products;
			})
			.catch(function (err) {
			 console.log(err);
			});
		});
	}
	setTimeout(function(){
		$scope.showBuy();
	},1000);

```

### Type of product you are working with consumable/non-consumable/subscription
The type of product is consumable

### Version of cordova
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    Cordova Platforms : android 6.1.2 ios 4.3.1
    Ionic Framework   : ionic1 1.3.2

System:

    Node  : v6.11.3
    npm   : 3.10.10 
    OS    : macOS Sierra
    Xcode : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro
### Version of iOS/Android
iOS 11

###

![screen shot 2017-09-27 at 18 02 11](https://user-images.githubusercontent.com/22498435/30924361-d07aa678-a3ae-11e7-8647-07dcabadc04a.png)

**Comment by Allan-Nava** [comment]
I also have this problem:
![screen shot 2017-09-27 at 18 23 29](https://user-images.githubusercontent.com/22498435/30925103-11263dde-a3b1-11e7-9fdc-6ab1194f71b0.png)

**Comment by moritzgloeckl** [comment]
Fix your imports an look at how to install the plugin, the error is not coming from the plugin itself.

**Comment by Allan-Nava** [comment]
@moritzgloeckl Now I get this error:

> 2017-09-28 12:06:33.990805+0200 InAppPurchases[3546:1660532] RMStore: products request received response  
> 2017-09-28 12:06:33.990956+0200 InAppPurchases[3546:1660532] RMStore: invalid product with id singolaPartitaSerieC
