### ISSUE TITLE
Error retrieving SKU details in Android <5.1.1

### ISSUE THREAD

**Issue by GPerezLZ** [AlexDisler/cordova-plugin-inapppurchase#179]
Please include:

### Your code / steps to reproduce
```
inAppPurchase.getProducts(['com.xxxxxxxxxx.20']).then(function (products) {
            // Muestro el listado de productos posibles
            $.each(products, function (i, item) {
                $('#sCantidad').append($('<option>', {
                    value: item.productId,
                    text: item.title
                }));
            });
        }).catch(function (error) {
            log(error);
        });
```
### Console output
Error retrieving SKU details

### Type of product you are working with consumable/non-consumable/subscription
consumable

### Version of cordova
7.0.1

### Version of iOS/Android
The problem occurs in **Android versions smaller than 5.1.1**

What is the minimum version of android for the plugin?

**Comment by moritzgloeckl** [comment]
Well, this plugin uses the InAppBilling Library V3, which was [released](https://developer.android.com/google/play/billing/versions.html) in February 2013. Android 4.4 has been released in October 2013. It really boils down to the Google Play client you're using, which should be at least `3.9.16` for in-app items and `3.10.10` for subscriptions.

**Comment by GPerezLZ** [comment]
Now I understand, this is something new for me. Can I solve this problem somehow or simply on phones with Android versions smaller than 5.1.1 I will not be able to show my products?

Thank you very much!

**Comment by moritzgloeckl** [comment]
Well you can modify this plugin to use a lower version of the InAppBilling Library.
