### ISSUE TITLE
PGB error "plugin unsupported: cordova-plugin-inapppurchase" 

### ISSUE THREAD

**Issue by caleb87** [AlexDisler/cordova-plugin-inapppurchase#18]
I'm not sure if this is an issue with Phonegap or the plugin. When I try to use the plugin on Phonegap Build, I get the error:

When I build on PGB, I get the error: plugin unsupported: cordova-plugin-inapppurchase 

I uploaded it as a private plugin. 

I tried the following:
<gap:plugin name="cordova-plugin-inapppurchase" spec="0.6.0" source="pgb" />
<gap:plugin name="cordova-plugin-inapppurchase" source="pgb" />

**Comment by aesculus** [comment]
I used this:
<gap:plugin name="cordova-plugin-inapppurchase" source="npm" />

and put the manifest.json file in the root as was requested in the www folder. It did not work there.

Worked ok for Android and iOS
