### ISSUE TITLE
how to detect if user selects CANCEL when the app-store asks him if he wants to purchase this?

### ISSUE THREAD

**Issue by halukkaramete** [AlexDisler/cordova-plugin-inapppurchase#182]
This is for the iOS for sure, but may also apply to Android. 

The error message fired when the user selects CANCEL at the time of purchase is "Cannot connect to iTunes Store" which is error code 2. 

But is it really?

The fact of the matter here is that the user has selected the cancel option and that is why we did not connect to the store. So, this is not a matter of "cannot" but a matter of "chose-not-to". 
Therefore, there is no point of displaying "Something Went Wrong". ( IMO )

Is there any way to detect the fact if the user has chosen the CANCEL option? 
With that, I can display a more appropriate message. That's the plan. 

Thank you

**Comment by jbgomez21** [comment]
Hi @halukkaramete 

This is my code for that:

            this.purchase.subscribe(productId)
                .then((purchase: any) => {
                    loading.dismiss();
                })
                .catch(error => {
                    loading.dismiss().then(_ => {
                        if (error && error.errorCode !== 2) {
                            //Error
                        } else {
                            //Cancel 
                        }
                    });
                });

Regards

**Comment by halukkaramete** [comment]
Yes. That does it. errorCode == 2 is the CANCEL. 
Thank you for your reply.

**Comment by halukkaramete** [comment]
When do we get errorCode is not equal 2? 
Can I say that it it is when Busy Network? 
Is there a list that I can look up to map error Codes to friendly messages such as code 3 is this, and 4 is that? Thank you

**Comment by halukkaramete** [comment]
Once I put the app on the app store, I get an instant message reporting me **_Busy Network_** message - every single time I wanted to initiate the buy process. 
( Please see the code segment below ). 

It's impossible to buy the app now. 

What's surprising is that I was not getting that output when we were testing the app on the sandbox account. Any comments on this? 

```
.catch(function (err) {
    $ionicLoading.hide();
    if (err.errorCode == 2) {
      // user just changed his mind, he does not want to buy. this is not an error!
    } else {
      //check if err is 2
      $ionicPopup.alert({
        title: 'Cannot connect to App Store now.',
        template: 'Busy Network...'
      });
    }
```
