### ISSUE TITLE
Update documentation needed

### ISSUE THREAD

**Issue by stephenprn** [AlexDisler/cordova-plugin-inapppurchase#183]
Hello,

This is not an issue but a request: please update the documentation about the inAppPurchase.getProducts(productIds) function. 
You tell that the productIds array must be 
`['com.yourapp.prod1', 'com.yourapp.prod2', ...]`
I fact, it has to be 
`['prod1', 'prod2', ...]`
I tried for one or two hours with the first synthax checking what I was doing wrong and reading again and again the documentation and finally found the issue on a stackOverFlow subject.

By the way, thanks for your plugin, it's working great when well set-up 👍

**Comment by moritzgloeckl** [comment]
@stephenprn You're correct for Android and the Google Play Store, but for the Apple App Store you need to prepend your package name.
