### ISSUE TITLE
IOS - Product returns empty

### ISSUE THREAD

**Issue by redeleon** [AlexDisler/cordova-plugin-inapppurchase#184]
Hi Guys,

Kinda new here and a newbie on cordova/phonegap apps. 

I have set up my app to use this plugin and have this code to try it out
`function inAppPurchases(){
      inAppPurchase.getProducts(['com.growmymusic.digitalmarketing']).then(function (products) {
        console.log(products);
      }).catch(function (err) {
        console.log(err);
      });
    }`

However, when I am trying to debug my app, products return as an empty array.
am I doing something wrong?

1. Does the in app purchase on itunes connect have to be approved? mine is set to "missing metadata" because I haven't uploaded a screenshot yet.
2. Does the app need to be published or passed the review for this to work? currently mine is rejected since Apple wanted to incorporate IAP on my app.

**Comment by FiveHundredMiles** [comment]
check out issue #148

**Comment by redeleon** [comment]
@FiveHundredMiles 
Thanks for this, I did the Paid Applications Contract and I can see the IAP now.
iOS sure has a lot of requirement.

**Comment by redeleon** [comment]
Alright now I'm having problems
I have a total of 5 In App Purchase Products available
4 of those are subscriptions
1 is a Non-Consumable

the problem now is that I can only get the Non-Consumable product and all of the subscription items aren't there.  returns an array with length of 1 instead of 5.

all are cleared for sale
