### ISSUE TITLE
Adding BILLING to APK

### ISSUE THREAD

**Issue by howardowens** [AlexDisler/cordova-plugin-inapppurchase#186]
I'm struggling to get BILLING added to my APK, per this message on the `In-App Products` tab:

`To add in-app products, you need to add the BILLING permission to your APK`

I added the base 64 string to manifest.json, though since I couldn't find an example of the manifest.json file complete, I don't know if I did it right.  All I have is

`{ "play_store_key": "key" }`

On the page.

There are instructions out there for adding BILLING through the extras folder in SDK manager, but I'm not getting that option.  

Not sure where to go from here.  I realize this isn't an issue with the plugin, but hoping to get some help here and perhaps get an answer posted that helps the next person who runs into the issue.

Some clarity in the instructions for the plugin might help with this issue.

**Comment by howardowens** [comment]
anybody, any help?

**Comment by moritzgloeckl** [comment]
@howardowens 

What exactly do you need help with? There are examples on how to use this plugin in the `README.md`

**Comment by howardowens** [comment]
as I say, I addedthe base 64 string to manifest.json per the readme.md

`{ "play_store_key": "key" }`

When I upload my APK to Google, I'm stilling getting a message that says

`To add in-app products, you need to add the BILLING permission to your APK`

This link contains more information about my struggle to add BILLING through Android Studio (with no answer yet). https://stackoverflow.com/questions/47128673/android-studo-3-0-sdk-manager-cant-find-extras?noredirect=1#comment81208519_47128673

**Comment by howardowens** [comment]
One of my questions is, is there more to manifest.json than just adding the line 

`{ "play_store_key": "key" }`

with the proper key, of course.

Right now, that's the online line in my manifest.json.

**Comment by moritzgloeckl** [comment]
@howardowens 

Are you developing a native Java Android Application? Because it really sounds like you do.

**Comment by howardowens** [comment]
Nope, Cordova

**Comment by moritzgloeckl** [comment]
@howardowens 

I've checked your SO question, first of all please stop fiddling around with Android Studio, you don't really need the SDK Manager or Android Studio for anything else, other than native code and debugging in the emulator. 

Second, the plugin should do everything for you, as well as adding `<uses-permission android:name="com.android.vending.BILLING" />` to `AndroidManifest.xml`. This is what Google is complaining about. It doesn't care about your `manifest.json`, all it wants is the permission in the `.xml`. So add the plugin via the command line, call `cordova prepare` and check the manifest please.

**Comment by howardowens** [comment]
I'll give that a try ... It's been a couple of months since I went down the Android Studio path, so I forgot what led me there, but I think it started with not being able to compile and run on my device from terminal with cordova run android ... and tracking down the errors ... the recommendations took me to this place.

There really aren't good instructions out there that are current to help me along, so I just hit a problem, and google and google until I find an answer, or I wind up in a place like this to ask a question.

I already have the plugin installed.  It's working in iOS (my iOS app is launched)

As for Android Studio ... who knows what I've got going on that may have me stuck there, now.  And I don't know how to create a signed APK except through it.

**Comment by howardowens** [comment]
So I opened AndroidManifest.xml scrolled there and 

`<uses-permission android:name="com.android.vending.BILLING" />`

is already there.  

I never consciously added it.

**Comment by moritzgloeckl** [comment]
@howardowens 

That's because the plugin added it automagically for you :)

**Comment by howardowens** [comment]
So it's been there all along and Google is till telling me I need permissions in my APK

**Comment by moritzgloeckl** [comment]
@howardowens 

Well there could be multiple things leading to this, wrong APK for example. When you create your APK, I would suggest decompiling it again (google "online APK decompiler") and check the `AndroidManifest.xml` in the decompiled APK if it really includes the permission.

I'm now closing this, as it's not really an issue with this plugin, and suggest moving this to StackOverflow!

**Comment by howardowens** [comment]
Unless I'm misunderstanding something about in-app products in the Google Play Console.  

My expectation is to create the products in the console, like I would with Apple, and then reference them in code with the appropriate IDs.  

Currently, I have no way to create in-app purchase produces in Play Console and this message telling me to I need to add BILLING to my SDK.

**Comment by moritzgloeckl** [comment]
@howardowens 

Ah okay I see, if I recall the process correctly, I think you first need to set up a merchant account, and then upload **any** APK with the billing permission for it to enable and be able to add products.

**Comment by howardowens** [comment]
Thanks ... I know you want to move this ... but to close the loop so to speak ... your decompile suggestion showed me that what is being compiled is the AndroidManifest.xml from Android Studio, not the one in my platforms/android folder ... so that probably explains the issue.

So, I'm going to try to figure out how to compile a signed APK from the terminal using cordova.

**Comment by moritzgloeckl** [comment]
Great, good luck 👍  :)!

**Comment by howardowens** [comment]
Thanks for your help.
