### ISSUE TITLE
Can you create a new RELEASE?

### ISSUE THREAD

**Issue by olaferlandsen** [AlexDisler/cordova-plugin-inapppurchase#187]
is necessary to get alfa, rc, beta and stable versions

**Comment by biesbjerg** [comment]
+1
I need the new currency and priceAsDecimal properties of IAPS. Please publish a new version to NPM!

**Comment by AlexDisler** [comment]
Just published

**Comment by biesbjerg** [comment]
Thank you, Alex! Very much appreciated!
