### ISSUE TITLE
Not working in production!?

### ISSUE THREAD

**Issue by peterel** [AlexDisler/cordova-plugin-inapppurchase#188]
All was working fine during development, even purchases. But as the app went live I just come to the .catch(function (err) clause...every time. Any idea what could have changed from development to live anyone?

Thanks in advance.

### Your code / steps to reproduce
```
inAppPurchase
	.getProducts(['X', 'Y', 'Z'])
	.then(function (products) {
	    doStuffWithProducts....
	})
	.catch(function (err) {
	    somethingBroke();
	});
```
### Console output
While developing all was good. Both in simulator and on device. Made a lot of purchases as testuser. But as the app went live the .catch gets called every time!

### Type of product you are working with consumable/non-consumable/subscription
Consumable

### Version of cordova
6.5
### Version of iOS/Android
Minumum 8

**Comment by moritzgloeckl** [comment]
Hard to tell without an error message...

**Comment by peterel** [comment]
@moritzgloeckl Good point :) See below. Please note that all worked on device during development, its just now when it went live that its breaking.

Thanks.

This is the error:
...
{'sourceURL': 'file:///var/containers/Bundle/Application/08601791-E022-46EC-B807-37396B9F459A/Path/To/file.js', 'line': 159, 'column': 36}
...

The code there is:
....
function initializeStore() {
    inAppPurchase
	.getProducts(['product1', 'product2', 'product3'])
	.then(function (products) {
	    var1 = products[2]['title']; //THIS IS LINE 159 (WHERE IT BREAKS)
	    var2 = products[2]['price'];
	    var3 = products[0]['title'];
	    var4 = products[0]['price'];
	    var5 = products[1]['title'];
	    var6 = products[1]['price'];   
	    /*
	      [{ productId: 'com.yourapp.prod1', 'title': '...', description: '...', currency: '...', price: '...', priceAsDecimal: '...' }, ...]
    */
	})
	.catch(function (err) {
	    sendEmail("Error in init IAP", err);
	});
}
...

Any ideas?

Pete

**Comment by moritzgloeckl** [comment]
```
{'sourceURL': 'file:///var/containers/Bundle/Application/08601791-E022-46EC-B807-37396B9F459A/Path/To/file.js', 'line': 159, 'column': 36}
```

Is this the only thing that happens? I mean there's not much that could go wrong at this line, so probably:

- `products` is null
- index 2 doesn't exist
- `var1` is not defined?

**Comment by peterel** [comment]
Yes, this is the only thing that happens. Nope, all was fine during
development and now this, very confusing. That’s why I wanted to ask if
there is something “stupid” that could be causing this? Eg a setting I
missed (test - production). I see that there is some metadata missing in
iTunes for these products but since all worked during development I thought
all would be good live too. Could that be causing this?

Thanks,

Peter

**Comment by moritzgloeckl** [comment]
I'm a primarily an Android Dev so I can't really tell, because I only used the App Store once, so I might not be the right person to ask. Sorry!

**Comment by peterel** [comment]
I just tried it out again in xcode. All works well there! But its broken live!? Very strange and very troublesome as Im clueless in what to do. Please, has anyone come across this? This is for Push Penguin app, iOS. See below for screenshot from app and from xcode just now:
From simulator:
![simulator screen shot - iphone 6 - 2017-11-17 at 23 20 12](https://user-images.githubusercontent.com/24371993/32971576-1b4fd17a-cbee-11e7-8d7e-f3ec97501051.png)
From live app:
![img_8134](https://user-images.githubusercontent.com/24371993/32971644-6bfe5b78-cbee-11e7-95d5-abccad0ae59b.PNG)

**Comment by fizcoder** [comment]
Was this resolved? I am in the process of finishing off an app for a client and I've been testing the in-app purchase. It seems sometimes on iOS the first time you attempt to purchase it fails but then it works and sometimes it works fine the first time. However this is in development/test mode. I've not tried it on a live app.

**Comment by peterel** [comment]
No, its not resolved. Still at a loss here. Really no idea how to fix this.
Any ideas would be appreciated!

Peter

**Comment by moritzgloeckl** [comment]
@peterel 
I really want this fixed, but we need more debug infos or errors to work with, because everything looks fine to me, at least code-wise. You could also try building a native application just to see if the plugin or some App Store setting is the culprit.

**Comment by peterel** [comment]
@moritzgloeckl 
Thanks. I do declare and use the variables globally. Could that cause this? Just very strange that something works in simulator and device on test but not live...very strange. The full code is below. Do you see anything there that could be causing this behavior?

```
//global product data
var var1;
var var2;
var var3;
var var4;
var var5;
var var6;

function initializeStore() {
    inAppPurchase
	.getProducts(['product1', 'product2', 'product3'])
	.then(function (products) {
	    var1 = products[2]['title'];
	    var2 = products[2]['price'];
	    var3 = products[0]['title'];
	    var4 = products[0]['price'];
	    var5 = products[1]['title'];
	    var6 = products[1]['price'];   
	    /*
	      [{ productId: 'com.yourapp.prod1', 'title': '...', description: '...', currency: '...', price: '...', priceAsDecimal: '...' }, ...]
    */
	})
	.catch(function (err) {
	    sendEmail("Error in init IAP", err);
	});
}
```

Also, regarding "You could also try building a native application just to see if the plugin or some App Store setting is the culprit." How do I do that? Its in live where it breaks. I cant do a new, separate, native App, release and get it approved for iOS just to test this. Seems a bit too much and far simpler to try another IAP plugin. Or am I misunderstanding your request here?

**Comment by moritzgloeckl** [comment]
@peterel 

It could be that it's the plugins fault but honestly I think it's because of the App Store. I found [this](https://forums.developer.apple.com/thread/13324) here and notice especially this part:

> If you did not select IAPs for inclusion with your binary then you have not submitted them for approval.  IAPs that have not been submitted for approval and approved will work in the sandbox environment in test flight and on the simulator but will not appear in the production environment.

Can you please double check your App Store settings?

Thanks!

**Comment by peterel** [comment]
Hmm, that could be it. Im really not sure what to do to check that though. I know you are an Android dev so maybe not you either. Ill see if I can find some guide for this. Otherwise, anyone that knows what "setting" Ill need to check?

**Comment by moritzgloeckl** [comment]
Closing this for now.
