### ISSUE TITLE
Android buy() returns error "The item you requested is not available for purchase"

### ISSUE THREAD

**Issue by caleb87** [AlexDisler/cordova-plugin-inapppurchase#19]
I can getProducts to show up (first thing that happens). I can restorePurchases() which shows an active but canceled subscription I created with a different plugin.

When I use buy/subscribe on Android, I keep getting the error "The item you requested is not available for purchase."

My test code:
```
function buyProduct() {
	inAppPurchase.buy('pp.consum1').then(function(data) {
		console.log(data);
		//return inAppPurchase.consume(data.productType, data.receipt, data.signature);
	}).catch(function (err) {
		console.log(err);
	});
}
function buySubscription() {
	inAppPurchase.subscribe('pp.subscription_1').then(function(data) {
		console.log(data);
		//return inAppPurchase.consume(data.productType, data.receipt, data.signature);
	}).catch(function (err) {
		console.log(err);
	});
}
function restorePurchases() {
	inAppPurchase.restorePurchases().then(function(data) {
		console.log(data);
		//return inAppPurchase.consume(data.productType, data.receipt, data.signature);
	}).catch(function (err) {
		console.log(err);
	});
}
function getReceipt() {
	inAppPurchase.getReceipt().then(function(data) {
		console.log(data);
		//return inAppPurchase.consume(data.productType, data.receipt, data.signature);
	}).catch(function (err) {
		console.log(err);
	});
}
function initializeStore() {
	inAppPurchase.getProducts(['pp.subscription_1', 'pp.consum1'])
  .then(function (products) {
    console.log(products);
    /*
       [{ productId: 'com.yourapp.prod1', 'title': '...', description: '...', price: '...' }, ...]
    */
  })
  .catch(function (err) {
    console.log(err);
  });	
}
```
The error output is:
Object {code: -5, message: "Purchase Cancelled", text: "User canceled. (response: -1005:User cancelled)", response: -1005}

Object 
description: "unlimited subscription" 
price: "$19.99" 
productId: "pp.subscription_1" 
"title: "Subscription"
....

This occurred on a managed product, and a monthly subscription. 

Cordova Version  cli-6.0.0

Android 5.0.1 (Physical HTC M8)

Edit:

Also, 
1) products are both Active
** http://stackoverflow.com/questions/13117081/the-item-you-requested-is-not-available-for-purchase

2) My user is a tester
http://stackoverflow.com/questions/32391047/item-you-requested-is-not-available-for-purchase-android-in-app-billing

3) My versionCode is the same on the Android store
http://stackoverflow.com/questions/11020587/in-app-billing-item-requested-not-available-for-purchase

4) I can switch out the plugin for cc.fovea.cordova.purchase which will work for buying products.

**Comment by caleb87** [comment]
I deleted the app, uploaded a new build on the alpha store and it worked. Not sure exactly what the issue was.

A check list i found in case others run into this problem:
Make sure to upload the signed APK to developer console.
Make sure to install the signed APK on your device not launch the app in the debugger.
Make sure to create a test account in your developer console.
Make sure to sign in your device with your test account.
Make sure to create in app billing in your developer console and finally activate the item from the console!!!
Make sure real credit card details are on file and not expired

**Comment by AlexDisler** [comment]
Glad you got it working, thanks for the list :+1:

**Comment by skotturi** [comment]
Would like to add to the list, you also need to make sure that you opted into testing with the test account... simply adding the account email to your Settings > Account > Testers isn't sufficient. 

The Opt-in URL under the Alpha config, you gotta copy n paste that into a browser in which you're logged into that google account (or phone).

**Comment by MrAlshahawy** [comment]
Help needed regards the same problem, When I install my app with a higher version than the one on the store I get the same error, sometimes I distribute a higher version on other places before the store and I want to give the users the ability to buy the items to unlock features. How could I solve that? And why the version number gets in the way?
