### ISSUE TITLE
Not an issue, but a concerning question

### ISSUE THREAD

**Issue by rafaeldcastro** [AlexDisler/cordova-plugin-inapppurchase#192]
Can I make the user purchase an item and receive a file/files to update his app with the product?

**Comment by moritzgloeckl** [comment]
Sorry, but this is not Stackoverflow.

**Comment by rafaeldcastro** [comment]
Tell me about it... Even there I can't resolve this question.
At least you were quick to aswer it :)

Anyway, if the plugin can do, next time, please describe ALL of its capabilities on the readme.

Thanks for your time :)

**Comment by moritzgloeckl** [comment]
This plugin is just a JS-wrapper for the corresponding Android & iOS libraries.

You'll likely need to setup a server, send your purchase token to the server, let the server check it against Google & Apple, and then provide the download with a unique, one-time URL.
