### ISSUE TITLE
Not finding inAppPurchase on iOS

### ISSUE THREAD

**Issue by cdcv** [AlexDisler/cordova-plugin-inapppurchase#193]
Not able to find inAppPurchase, getting: 

inAppPurchase.getProducts is not a function

Having run it a bunch of times now, sometimes the inAppPurchase object is available, but has initialized:false, and when I try to run the getProducts function it says it's not a function.

BTW, this is all after waiting >10s after app startup.

### Code
Used the code straight from the example:
    inAppPurchase
        .getProducts('xxxxx our bundle id xxxx')
        .then(function (products) {
            console.log(products);
        })
        .catch(function (err) {
            console.log(err);
        });

### Console output
TypeError: inAppPurchase.getProducts is not a function. (In 'inAppPurchase.getProducts('com.brainful.fanata')', 'inAppPurchase.getProducts' is undefined)

I get this output in the Safari console when running the iOS app on an iphone with the cordova app installed and running on the mobile device.

### Type of product you are working with consumable/non-consumable/subscription
At this point, just trying to get the plugin working.

### Version of iOS/Android
iOS 11.0.3

**Comment by moritzgloeckl** [comment]
Please check the `README.md` next time, you're using the `.getProducts` method wrongly!
It's `.getProducts(['com.yourapp.prod1', 'com.yourapp.prod2', ...])`, it's expecting an Array not a string! There is no `.getProducts(string)` method.
