### ISSUE TITLE
get purchased item when device offline

### ISSUE THREAD

**Issue by jhautot** [AlexDisler/cordova-plugin-inapppurchase#194]
Hello,

Is there a way to get the purchased item when no internet connection.

I'm using 

inAppPurchase
      .restorePurchases()
      .then(function (datas) {
        console.log(JSON.stringify(datas));
        datas.forEach(function(data){
            if (data["productId"] == "premium") {
            }
        });
      })
      .catch(function (err) {
        console.log(err);
      });

but it is only working when internet is on.

Thank you

**Comment by moritzgloeckl** [comment]
Of course it doesn't work when there's no internet, it needs a working connection to Google Play!

**Comment by jhautot** [comment]
Hello, thanks for your comment. Normaly an app is supposed to know even without internet if an item has been bought. I think it should work by using cache information in playstore locally on the phone.
Could you tell me if there is such a thing with this plugin?

Thak you
