### ISSUE TITLE
Consume then validate in one promise chain

### ISSUE THREAD

**Issue by mklilley** [AlexDisler/cordova-plugin-inapppurchase#2]
Hi,

Thanks for taking the time to write this plugin, I have only been looking at it briefly but am finding it infinitely easier to understand that the other ones out there....shall name no names :-)

I just have a question really.  I am looking at your example:

` 
  inAppPurchase
    .buy('com.yourapp.consumable_prod1')
    .then(function (data) {
      return inAppPurchase.consume(data.productType, data.receipt, data.signature);
    })
    .then(function (data) {
      console.log('product was successfully consumed!');
    })
    .catch(function (err) {
      console.log(err);
    });`

I am wondering, after the product has been consumed is the data returned from `inAppPurchase.consume(data.productType, data.receipt, data.signature);` the same as that returned from ` inAppPurchase
    .buy('com.yourapp.consumable_prod1')`.  It seems to be suggested to be the case, but as I went through the source code it was not immediately apparent that nativeCall to the consume function returns the same data as for the buy function.

Essentially what i'd like to do is consume the product then afterwards validate it as a nice promise chain and im worried that if i consume first ill lose the receipt and signature data.

I hope that makes sense

Thanks for your time

Matt

**Comment by AlexDisler** [comment]
Hi Matt,

```consume()``` returns a promise that resolves to nothing, I'll update the readme to reflect that. Thanks for pointing it out.

You can still keep the data after the purchase:
```js
var data;
inAppPurchase.buy('com.yourapp.consumable_prod1')
  .then(function (_data) {
    data = _data;
    return inAppPurchase.consume(data.productType, data.receipt, data.signature);
  }).then(function () {
    console.log('product was successfully consumed!');
    console.log(' validation data:');
    console.log(data);
  }).catch(function (err) {
    console.log(err);
  });
```
Or did you mean something else?

**Comment by mklilley** [comment]
Yeah that makes sense now.  Thanks
