### ISSUE TITLE
Invalid receipt. Status code: 21002

### ISSUE THREAD

**Issue by idimni** [AlexDisler/cordova-plugin-inapppurchase#21]
1) Plugin retrurn  
`receipt  = 'MII67gYJ...IF8Q'`

2) Validator PHP https://github.com/chrismaddern/iOS-Receipt-Validator-PHP always return 
`Sandbox Invalid receipt. Status code: 21002`

### Your code / steps to reproduce
```js
inAppPurchase
  .buy('my_app_id')
  .then(function (data) {
        //send data.receipt my server
  })
  .then(function () {
    console.log('product was successfully consumed!');
  })
  .catch(function (err) {
    console.log(err);
  });
```
### Type of product you are working with consumable/non-consumable/subscription
non-consumable

### Version of cordova ios
6.0.1

**Comment by AlexDisler** [comment]
Make sure that the in app purchases are added on the app's version page:

![in app purchases - ios](https://cloud.githubusercontent.com/assets/575199/14919005/afab2dec-0df4-11e6-9b9a-565a1fa40f2f.png)

I had the same error once until I noticed that I forgot to attach the products to the app.

Also, I recommend this php library: https://github.com/aporat/store-receipt-validator
