### ISSUE TITLE
No need to somehow finish products?

### ISSUE THREAD

**Issue by Defcon0** [AlexDisler/cordova-plugin-inapppurchase#213]
Hello,

maybe I'll switch from https://github.com/j3k0/cordova-plugin-purchase to this plugin. What's confusing me a bit is why no products are ever "finished" so that it's not pending anymore. Is that **automatically** done if then() is called after subscribe() had been called?

Thanks in advance for any help!

**Comment by Reactor13** [comment]
The same question.

One of our users has already faced the problem of an unfinished purchase. So he can't restore it and can't purchase again, because iTunes says - "Purchased already done. It will be restored for free" - and plugin don't handling this status.

**Comment by Defcon0** [comment]
Seems to be the normal way Apple handles this. Too bad :(
