### ISSUE TITLE
Normalize error code property on error responses

### ISSUE THREAD

**Issue by dougflip** [AlexDisler/cordova-plugin-inapppurchase#23]
I've noticed that when the native layers report back errors the property containing the error code is slightly different. On iOS the error object reports the error code as `{ errorCode }` while on Android it is reported as `{ code }`. This definitely isn't a bug, but it seems like it could be a nice improvement to add consistency across the platforms. What do you think?

If this is something that should be implemented in the JS layer I'd be happy to take a stab and submit a PR.

**Comment by AlexDisler** [comment]
Yeah that's a good idea, I've been planning to do that at some point. A PR is welcome of course, thank you.
