### ISSUE TITLE
getProducts() & buy() functions returns errors - ionic 3

### ISSUE THREAD

**Issue by mrpower55** [AlexDisler/cordova-plugin-inapppurchase#278]
Hello There,

i try to use this plugin i have added my products on play store account and also on in app purchase section on itunes connect but when i try to use getProducts function it is showing me this error:

 {"code":-2,"message":"Unable to initialize billing: IabResult: Error checking for 
            billing v3 support. (response: 3:Billing Unavailable)","text":"Error checking for billing v3 support. 
            (response: 3:Billing Unavailable)","response":3,"errorCode":-2}

also when i try to use buy function directly it is return this error:
{"code":-3,"message":"Billing is not initialized","errorCode":-3}

i want to mention that i made my test on android device for both debug version and internal testing on account and both return same error

here is my code:

      let productID = '10.99';
      console.log("productID: ", productID);
      this.iap.getProducts([productID]).then(function (products) {
        console.log("products success: ", JSON.stringify(products));
      }).catch(function (err) {
        console.log("products err: ", JSON.stringify(err));
      });

      this.iap.buy(productID).then(function (data) {
        console.log("buy success: ",JSON.stringify(data));
      }).catch(function (err) {
        console.log("buy err: ",JSON.stringify(err));
      });

on ios when using getProducts it is back with empty array
but if i use buy function it is back with error:
{"errorMessage":"Unknown product identifier","errorCode":100}

so please if anyone face same problem and can help me please replay to me here

waiting for your help guys

thanks

**Comment by mrpower55** [comment]
@AlexDisler please help

**Comment by Steco17** [comment]
Hi guys, any fix to this?

**Comment by maximilianmeier** [comment]
i'm using ionic 4 and adding the manifest file to this folder did the job for me
`android/app/src/main/assets/www/manifest.json`
