### ISSUE TITLE
inAppPurchase and Typescript

### ISSUE THREAD

**Issue by biesbjerg** [AlexDisler/cordova-plugin-inapppurchase#28]
It would be nice to have typescript definitions for this plugin. Are they by any chance available somewhere?

![image](https://cloud.githubusercontent.com/assets/230182/15451114/4e6c299c-1fb4-11e6-9142-3810d2d5659f.png)

**Comment by AlexDisler** [comment]
Is there a cordova plugin with typings for reference?

Or should it be added to the typings registry?

**Comment by biesbjerg** [comment]
Actually it looks like it should go in the registry: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/cordova/plugins

Sorry I'm not more helpful but I'm still pretty new to Cordova, typescript etc

**Comment by dfibuch** [comment]
You can just declare it within your module and access it directly:

`declare var inAppPurchase: any;`

so it would be:

```
module MyModule {
    declare var inAppPurchase: any;

    export class MyClass{
        public loadProduct(): void {
             ....
        }
    }
```

You won't get intellisense but at least you won't get errors.

**Comment by marcusforsberg** [comment]
If you're using Ionic 2, this plugin has been added to ionic-native so you can use it easily: http://ionicframework.com/docs/v2/native/inapppurchase/
