### ISSUE TITLE
As of April 20, 2020, latest fork branch.

### ISSUE THREAD

**Issue by Chadori** [AlexDisler/cordova-plugin-inapppurchase#290]
As of **April 20, 2020**, latest [fork branch](https://www.npmjs.com/package/cordova-plugin-inapppurchase-new).

**Latest Version:** `cordova-plugin-inapppurchase-new@1.4.2`.

- Fixed error with the `.aidl` file target.
- Patched to lift Google's 20 SKU limit.

_This version is made from the pull requests of selected forks._
I hope this helps others looking for a working `npm package` fix for this plugin.
And thanks to the authors of the pull requests used in this package.

**Comment by lilmnm-kamikaze-** [comment]
yup several others have also done this. i myself have it here on github and just include it from github.that way i can maintain it and not have to wait for others.

**Comment by Seanmclem** [comment]
I appreciate this. It fixes new bugs?

**Comment by Chadori** [comment]
Yes, it should.
Tested with our projects.
If I missed something, please specify and I'll patch it up.

**Comment by Seanmclem** [comment]
I don't fully understand that fork branch. It's just Issues? How is it a fork? How do I use it?
