### ISSUE TITLE
Can't find variable: inAppPurchase

### ISSUE THREAD

**Issue by fquirogam** [AlexDisler/cordova-plugin-inapppurchase#30]
I'm trying to use your plugin but I can't make it work because every time I run the app I always get "Error: can't find the variable inAppPurchase" and I've uninstalled and reinstalled the plugin several times but I'm still getting the same, even with the example code from your GitHub page.

Any ideas?

Thanks

**Comment by PimCoumans** [comment]
@fquirogam I'm experiencing the same problem, how did you fix this?

**Comment by cdcv** [comment]
I'm experiencing the same error.  What is the resolution? Thanks.

**Comment by fquirogam** [comment]
Wait for the plugin to be ready, adding a setTiemout would do the trick
