### ISSUE TITLE
iOS: Error when calling inAppPurchase.restorePurchases()

### ISSUE THREAD

**Issue by jrmyward** [AlexDisler/cordova-plugin-inapppurchase#5]
When attempting to implement `restorePurchases()` on iOS, the method fails with the following error:

```
RMStore: restore transactions finished
Restore error: TypeError: purchases.map is not a function. (In 'purchases.map', 'purchases.map' is undefined)
```

The IAP is a non-renewing subscription. I'm not sure if that matters or not. The `buy` functionality works without problem.

Here's the code producing the error:

```
$scope.restore = function () {
    $ionicLoading.show({ template: spinner + 'Restoring Purchases...' });
    inAppPurchase
        .restorePurchases()
        .then(function (data) {
            console.log("Restore: " + JSON.stringify(data));
        })
        .catch(function (err) {
            console.log("Restore error: " + err);
            $ionicLoading.hide();
        });
};
```

**Comment by AlexDisler** [comment]
Please try the new version 0.2.0 by reinstalling the plugin, should work now.

**Comment by jrmyward** [comment]
The error is gone, however, I now just get an empty array:

```
RMStore: restore transactions finished
Restore: []
```

**Comment by AlexDisler** [comment]
You mentioned that you are using non-renewable subscriptions, they cannot be restored.

http://stackoverflow.com/questions/23931586/does-non-renewing-subscription-requires-a-restore-button

**Comment by AlexDisler** [comment]
I'm closing this since the reported problem seems to be resolved but please re-open if you are still having issues.

**Comment by patrickhofer** [comment]
I also have this issue.
