### ISSUE TITLE
Subscription purchase returns error on Android (IAB returned null purchaseData or dataSignature)

### ISSUE THREAD

**Issue by DigitalMystery** [AlexDisler/cordova-plugin-inapppurchase#6]
When purchasing a subscription the purchase goes thru, but I receive an error back which is listed below.  From what I could find it looks like the error means: 
launchPurchaseFlow is called instead of launchSubscriptionPurchaseFlow 
I did post a question on your blog but figured here is more fitting for the issue.

-code
` $scope.buyProduct = function(productId) {
       inAppPurchase.buy(productId)
            .then(function (data) {
                $ionicLoading.show({
                    noBackdrop: false,
                    template: '<p class="icon ion-loading-a"><ion-spinner class="spinner-assertive" icon="bubbles"/></p><br />Loading'
                });
                //I do my own server calls here
            })
            .catch(function (err) {
                $ionicPopup.alert({
                    title: err.code,
                    content: err.message + ' ----- ' + err.response + ' ----- ' + err.text,
                    cssClass: 'my-custom-popup'
                });
            });
    }`

-output
could not complete purchase ----- 1008  ----- IAB returned null purchaseData or dataSignature
(response: - 1008:Unkown error)

-type
subscription

-version of Cordova
6.0.0

-version of Android
Android 5.1.1

**Comment by AlexDisler** [comment]
Yeah there's an issue with subscriptions on Android. The plugin should have an additional ```subscribe()``` function that will handle subscriptions instead of ```buy()```. It should call ```launchSubscriptionPurchaseFlow``` instead of ```launchPurchaseFlow ```. On iOS it can still call ```buy()``` so the api will be consistent.

I'll add it but probably won't have time in the next week or so, or if you can open a pull request that would be great.

**Comment by kristfal** [comment]
Just a quick question, does this prevent _any_ Android subscription to work, or is this an edge case?

**Comment by AlexDisler** [comment]
Any Android subscription

**Comment by DigitalMystery** [comment]
Sorry, I have been short on time lately with a project.  Great work though with this plugin.  Hopefully I get back around to where I can test it out some more.  Also, maybe in the future if you start to add windows support I will try to help out or give some $ to the cause.

**Comment by devtobo** [comment]
If anyone encounter this error, it might be related to your sandbox user. Try with a fresh sandbox user or even better a real user. Don't know exactly the reason why (maybe to many receipts or maybe when you cancel a sub it takes time to clean the sandbox user)...

**Comment by clampx** [comment]
I am facing the same issue. Is this still not resolved? Can I still not subscribe to any in app product in android?

**Comment by DigitalMystery** [comment]
The above issue was fixed back in 2016.  If this issue is happening again, maybe it has something to do with the latest updates to Android?  Aren't they rolling out some new changes to the Play Store?  If so that might be the culprit (just speculation).  I am currently re-testing my app with new changes, but not experiencing any issues yet.   I will let you know if I run into anything in the next day or two.  If not then I would create a new issue.....

**Comment by clampx** [comment]
@DigitalMystery Thanks for following up.
Following is the output if it helps in narrowing down

> D/CordovaActivity: Incoming Result. Request code = 0
D/CordovaInterfaceImpl: Sending activity result to plugin
E/IabHelper: In-app billing error: BUG: either purchaseData or dataSignature is null.
D/google.payments: Error: Could not complete purchase
D/CordovaActivity: Resumed the activity.

I have added subscription products on google play console and I am testing it on android test version. 
When I call the buy method all the google play dialogs work fine. On continuing I receive above mentioned error and not success

**Comment by rsweny** [comment]
I am also experiencing this error testing an alpha build. Here is a more detailed log:
```
06-11 13:46:19.701 10265-10265/? E/IabHelper: In-app billing error: BUG: either purchaseData or dataSignature is null.
06-11 13:46:19.746 10265-10265/? I/chromium: [INFO:CONSOLE(1)] "Err: {"code":-6,"message":"Could not complete purchase","text":"IAB returned null purchaseData or dataSignature (response: -1008:Unknown error)","response":-1008,"errorCode":-6}", source: file:///android_asset/www/build/main.js (1)
```

**Comment by DigitalMystery** [comment]
My only other guess at this point is to make sure you guys are calling subscribe to a subscription and buy on a product.  Mine worked fine when tested.  I have even had a couple of subscription since then (I do not make much money lol)

**Comment by rsweny** [comment]
Sorry.. that was it! Using the subscribe call instead of buy fixes it for me. Thanks for the tip.

**Comment by desmeit** [comment]
I have the same issue: "Could not complete purchase".
But I work with subscribe. Here is my code:

   ```
            inAppPurchase
		  .subscribe(productid)
		  .then(function (data) {
                          //
                  .catch(function (err) {
                 console.log(JSON.stringify(err));
                });
```

I found this:
https://stackoverflow.com/questions/16377755/google-play-in-app-purchase-returns-error-code-1008-null-puchasedata-or-datasi

It should have to do with launchSubscriptionPurchaseFlow.
Is there an other way to solve it? Thanks
