### ISSUE TITLE
Error retrieving Product : RMStore: invalid product with id

### ISSUE THREAD

**Issue by Kageyo** [AlexDisler/cordova-plugin-inapppurchase#60]
Hello, I created a simple button that will run my function test().
I of course added on iTunesConnect my in app purchases but can't seem to retrieve them.
Do you have any ideas where this might come from ?

thank you

### Your code / steps to reproduce
	$scope.test = function() {
		var productIds = ['1','2','3','4'];

		inAppPurchase
		  .getProducts(productIds)
		  .then(function (products) {
		    console.log(products);
		    $scope.products = products;
		  })
		  .catch(function (err) {
		    console.log(err);
		});

		console.log("test");
	}
### Console output

2016-08-19 15:06:08.877 MyApp[49941:8244696] Test function
2016-08-19 15:06:17.043 MyApp[49941:8244696] RMStore: products request received response
2016-08-19 15:06:17.043 MyApp[49941:8244696] RMStore: invalid product with id 3
2016-08-19 15:06:17.043 MyApp[49941:8244696] RMStore: invalid product with id 1
2016-08-19 15:06:17.043 MyApp[49941:8244696] RMStore: invalid product with id 4
2016-08-19 15:06:17.044 MyApp[49941:8244696] RMStore: invalid product with id 2

### Type of product you are working with consumable/non-consumable/subscription
Product 1,2,3 are subscription
Product 4 is non consumable

### Version of cordova

Cordova 6.2.0
### Version of iOS/Android

iOS 9.3

**Comment by paololabe** [comment]
Same issue, i tried with a consumable and a non consumable product id.
I'm using a sandbox email account.
cordova 6.1.1
iOS 9.3

**Comment by Kageyo** [comment]
@paololabe Hello, after desperately trying a lot of stuff, I found this : http://stackoverflow.com/questions/12736712/ios-in-app-purchases-sandbox-invalid-product-id

So I just set up the bank information in iTunes Connect and everything is working now 👍 
Hope it helps
