### ISSUE TITLE
Rejected from Google Play for Security Vulnerabilities

### ISSUE THREAD

**Issue by galcivar** [AlexDisler/cordova-plugin-inapppurchase#61]
Hi!

My App got rejected due two reasons, one because of using Cordova 4.0.0 (which I am in the process of updating), but the second says its due to **in-app billing** (using cordova-plugin-inapppurchase 1.0.0 "In App Purchase"), here's the response I got from Google:
> I understand you received a security alert about using a highly vulnerable version of in-app billing and Cordova. 
> If you'd like to know which of your apps are impacted. Please find the list below:
> IAP - com.google.android.gms.internal.cs
> com.google.android.gms.internal.cu
> com.google.android.gms.internal.cw
> Cordova - org.apache.cordova.CordovaWebView (4.0.0) 

> For more information about the vulnerability, please see: 
> IAP- https://support.google.com/faqs/answer/7054270
> Cordova - https://support.google.com/faqs/answer/6325474

Is there a solution for it or only updating Cordova will fix the issue for InApp Purchases aswell?

Thanks

**Comment by marcusforsberg** [comment]
@galcivar Did you ever solve this issue? I'm currently trying to implement this plugin for my app and hearing that you've been having security issues is worrying!

**Comment by galcivar** [comment]
@marcusforsberg It seemed it was related to an old Cordova version, not the plugin directly. I haven't had issues since I fully upgraded Cordova.
