### ISSUE TITLE
iOS non-consumable restoring issue

### ISSUE THREAD

**Issue by emmychen** [AlexDisler/cordova-plugin-inapppurchase#7]
This is for iOS non-cosumable in-app-purchase.  The purchase process works fine.  But when I try to do restore, I always got the error message says:  
 The error message is "Cannot connect to iTunes Store", "errorCode": 0

var restore = function() {
$ionicLoading.show({ template: spinner + 'Restoring Purchases...' });
            inAppPurchase
                .restorePurchases()
                .then(function (purchases) {
                    $ionicLoading.hide();
                    console.log(JSON.stringify(purchases));
                    $ionicPopup.alert({
                        title: 'Restore was successful!',
                        template: 'Check your console log for the restored purchases data!'+JSON.stringify(purchases)
                    });
                })
                .catch(function (err) {
                    $ionicLoading.hide();
                    console.log(err);
                    $ionicPopup.alert({
                        title: 'Something went wrong',
                        template: 'Check your console log for the error details '+JSON.stringify(err)
                    });
                });
}

This is non-consumable 
cordova version is 6.0.0
iOS version 9.x

**Comment by AlexDisler** [comment]
Are you getting this error on a simulator or on a device?

**Comment by emmychen** [comment]
I am using the real device.

**Comment by AlexDisler** [comment]
I've tested this on my device and it works for me.

This is a common problem with iTunes, unrelated to the plugin. You can try the solution(s) from here: http://stackoverflow.com/questions/7402801/cannot-connect-to-itunes-store-in-app-purchases

- log out of your production account
- make sure the products are cleared for sale
- add a test user
etc
