### ISSUE TITLE
Uncaught ReferenceError: Promise is not defined on Android 4.4

### ISSUE THREAD

**Issue by nathan6137** [AlexDisler/cordova-plugin-inapppurchase#9]
When using this with older version of android (android 4.4) Promise doesn't exist

### Here is what i get in Console output : 
`Uncaught ReferenceError: Promise is not defined `

### Type of product:
non-consumable

### Version of cordova
6.1.0

### Version of iOS/Android
Android 4.4

**Comment by fenta23** [comment]
Promises are not supported on 4.4: http://caniuse.com/#search=promise
you have to implement a polifill for this.
Have a look at https://github.com/stefanpenner/es6-promise or similar.

**Comment by dougflip** [comment]
Also, just in case you haven't used it before you may want to look into [Crosswalk](https://crosswalk-project.org/) as an alternative WebView. It will provide numerous features for Android 4.4 (at the cost of a larger APK).

**Comment by ketabi** [comment]
look at this:

https://stackoverflow.com/a/48203092/6200607
